# Generated by Django 3.1.14 on 2025-02-26 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20250226_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 26, 7, 34, 30, 26454, tzinfo=utc), null=True, verbose_name='Время появления'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 26, 7, 34, 30, 26454, tzinfo=utc), null=True, verbose_name='Время исчезновения'),
        ),
    ]
